# Generated by Django 2.2.2 on 2019-07-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
