# Generated by Django 2.2.2 on 2019-09-03 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190902_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='abouttheconference',
            name='link',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='callforpapers',
            name='link',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
