# Generated by Django 2.2.2 on 2019-09-03 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_importantdates_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abouttheconference',
            name='name',
        ),
        migrations.RemoveField(
            model_name='callforpapers',
            name='name',
        ),
    ]
