# Generated by Django 2.2.2 on 2019-09-03 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_contacts_organisers_speakers'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='CallForPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
                ('link', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
                ('link', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='ImportantDates',
            new_name='ImportantDate',
        ),
        migrations.RenameModel(
            old_name='Organisers',
            new_name='Organiser',
        ),
        migrations.RenameModel(
            old_name='Speakers',
            new_name='Speaker',
        ),
        migrations.DeleteModel(
            name='CallForPapers',
        ),
        migrations.DeleteModel(
            name='Contacts',
        ),
    ]
