# Generated by Django 2.2.2 on 2019-09-03 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190903_0421'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
            ],
        ),
    ]
