# Generated by Django 2.2.2 on 2019-09-03 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_accomodationandtravel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='link',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True),
        ),
    ]
