# Generated by Django 2.2.2 on 2019-09-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20190903_0503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='link',
        ),
        migrations.AddField(
            model_name='importantdate',
            name='highlighted',
            field=models.TextField(default=''),
        ),
    ]
