# Generated by Django 2.2.2 on 2019-09-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20190903_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
                ('title', models.CharField(default='', max_length=100)),
                ('highlights', models.TextField(default='')),
            ],
        ),
    ]
