# Generated by Django 2.2.2 on 2019-09-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomodationandtravel',
            name='link',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='importantdate',
            name='highlighted',
            field=models.TextField(default='', null=True),
        ),
    ]
