# Generated by Django 2.2.2 on 2019-09-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20190904_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationcontact',
            name='highlight',
            field=models.TextField(default='', null=True),
        ),
    ]
